/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/conghui/industrial_training/training/ref/demo_manipulation/src/collision_avoidance_pick_and_place/srv/GetTargetPose.srv
 *
 */


#ifndef COLLISION_AVOIDANCE_PICK_AND_PLACE_MESSAGE_GETTARGETPOSE_H
#define COLLISION_AVOIDANCE_PICK_AND_PLACE_MESSAGE_GETTARGETPOSE_H

#include <ros/service_traits.h>


#include <collision_avoidance_pick_and_place/GetTargetPoseRequest.h>
#include <collision_avoidance_pick_and_place/GetTargetPoseResponse.h>


namespace collision_avoidance_pick_and_place
{

struct GetTargetPose
{

typedef GetTargetPoseRequest Request;
typedef GetTargetPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetTargetPose
} // namespace collision_avoidance_pick_and_place


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::collision_avoidance_pick_and_place::GetTargetPose > {
  static const char* value()
  {
    return "465d51d8a3f39b4cd4049318ef31b315";
  }

  static const char* value(const ::collision_avoidance_pick_and_place::GetTargetPose&) { return value(); }
};

template<>
struct DataType< ::collision_avoidance_pick_and_place::GetTargetPose > {
  static const char* value()
  {
    return "collision_avoidance_pick_and_place/GetTargetPose";
  }

  static const char* value(const ::collision_avoidance_pick_and_place::GetTargetPose&) { return value(); }
};


// service_traits::MD5Sum< ::collision_avoidance_pick_and_place::GetTargetPoseRequest> should match 
// service_traits::MD5Sum< ::collision_avoidance_pick_and_place::GetTargetPose > 
template<>
struct MD5Sum< ::collision_avoidance_pick_and_place::GetTargetPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::collision_avoidance_pick_and_place::GetTargetPose >::value();
  }
  static const char* value(const ::collision_avoidance_pick_and_place::GetTargetPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::collision_avoidance_pick_and_place::GetTargetPoseRequest> should match 
// service_traits::DataType< ::collision_avoidance_pick_and_place::GetTargetPose > 
template<>
struct DataType< ::collision_avoidance_pick_and_place::GetTargetPoseRequest>
{
  static const char* value()
  {
    return DataType< ::collision_avoidance_pick_and_place::GetTargetPose >::value();
  }
  static const char* value(const ::collision_avoidance_pick_and_place::GetTargetPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::collision_avoidance_pick_and_place::GetTargetPoseResponse> should match 
// service_traits::MD5Sum< ::collision_avoidance_pick_and_place::GetTargetPose > 
template<>
struct MD5Sum< ::collision_avoidance_pick_and_place::GetTargetPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::collision_avoidance_pick_and_place::GetTargetPose >::value();
  }
  static const char* value(const ::collision_avoidance_pick_and_place::GetTargetPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::collision_avoidance_pick_and_place::GetTargetPoseResponse> should match 
// service_traits::DataType< ::collision_avoidance_pick_and_place::GetTargetPose > 
template<>
struct DataType< ::collision_avoidance_pick_and_place::GetTargetPoseResponse>
{
  static const char* value()
  {
    return DataType< ::collision_avoidance_pick_and_place::GetTargetPose >::value();
  }
  static const char* value(const ::collision_avoidance_pick_and_place::GetTargetPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COLLISION_AVOIDANCE_PICK_AND_PLACE_MESSAGE_GETTARGETPOSE_H
