(cl:defpackage robot_io-srv
  (:use )
  (:export
   "DIGITALOUTPUTUPDATE"
   "<DIGITALOUTPUTUPDATE-REQUEST>"
   "DIGITALOUTPUTUPDATE-REQUEST"
   "<DIGITALOUTPUTUPDATE-RESPONSE>"
   "DIGITALOUTPUTUPDATE-RESPONSE"
  ))

