/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/conghui/industrial_training/training/ref/demo_manipulation/src/robot_io/srv/DigitalOutputUpdate.srv
 *
 */


#ifndef ROBOT_IO_MESSAGE_DIGITALOUTPUTUPDATE_H
#define ROBOT_IO_MESSAGE_DIGITALOUTPUTUPDATE_H

#include <ros/service_traits.h>


#include <robot_io/DigitalOutputUpdateRequest.h>
#include <robot_io/DigitalOutputUpdateResponse.h>


namespace robot_io
{

struct DigitalOutputUpdate
{

typedef DigitalOutputUpdateRequest Request;
typedef DigitalOutputUpdateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DigitalOutputUpdate
} // namespace robot_io


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_io::DigitalOutputUpdate > {
  static const char* value()
  {
    return "5decc6a45bba41be52c4b7de53de20e7";
  }

  static const char* value(const ::robot_io::DigitalOutputUpdate&) { return value(); }
};

template<>
struct DataType< ::robot_io::DigitalOutputUpdate > {
  static const char* value()
  {
    return "robot_io/DigitalOutputUpdate";
  }

  static const char* value(const ::robot_io::DigitalOutputUpdate&) { return value(); }
};


// service_traits::MD5Sum< ::robot_io::DigitalOutputUpdateRequest> should match 
// service_traits::MD5Sum< ::robot_io::DigitalOutputUpdate > 
template<>
struct MD5Sum< ::robot_io::DigitalOutputUpdateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_io::DigitalOutputUpdate >::value();
  }
  static const char* value(const ::robot_io::DigitalOutputUpdateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_io::DigitalOutputUpdateRequest> should match 
// service_traits::DataType< ::robot_io::DigitalOutputUpdate > 
template<>
struct DataType< ::robot_io::DigitalOutputUpdateRequest>
{
  static const char* value()
  {
    return DataType< ::robot_io::DigitalOutputUpdate >::value();
  }
  static const char* value(const ::robot_io::DigitalOutputUpdateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_io::DigitalOutputUpdateResponse> should match 
// service_traits::MD5Sum< ::robot_io::DigitalOutputUpdate > 
template<>
struct MD5Sum< ::robot_io::DigitalOutputUpdateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_io::DigitalOutputUpdate >::value();
  }
  static const char* value(const ::robot_io::DigitalOutputUpdateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_io::DigitalOutputUpdateResponse> should match 
// service_traits::DataType< ::robot_io::DigitalOutputUpdate > 
template<>
struct DataType< ::robot_io::DigitalOutputUpdateResponse>
{
  static const char* value()
  {
    return DataType< ::robot_io::DigitalOutputUpdate >::value();
  }
  static const char* value(const ::robot_io::DigitalOutputUpdateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_IO_MESSAGE_DIGITALOUTPUTUPDATE_H
