/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/conghui/industrial_training/training/ref/demo_manipulation/src/robot_io/srv/DigitalOutputUpdate.srv
 *
 */


#ifndef ROBOT_IO_MESSAGE_DIGITALOUTPUTUPDATEREQUEST_H
#define ROBOT_IO_MESSAGE_DIGITALOUTPUTUPDATEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_io
{
template <class ContainerAllocator>
struct DigitalOutputUpdateRequest_
{
  typedef DigitalOutputUpdateRequest_<ContainerAllocator> Type;

  DigitalOutputUpdateRequest_()
    : request_type(0)
    , bit_index(0)
    , output_bit_state(false)  {
    }
  DigitalOutputUpdateRequest_(const ContainerAllocator& _alloc)
    : request_type(0)
    , bit_index(0)
    , output_bit_state(false)  {
    }



   typedef uint32_t _request_type_type;
  _request_type_type request_type;

   typedef uint32_t _bit_index_type;
  _bit_index_type bit_index;

   typedef uint8_t _output_bit_state_type;
  _output_bit_state_type output_bit_state;


    enum { COUNT = 8 };
     enum { SUCTION1_ON = 1 };
     enum { SUCTION2_ON = 2 };
     enum { COLLISION = 0 };
 

  typedef boost::shared_ptr< ::robot_io::DigitalOutputUpdateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_io::DigitalOutputUpdateRequest_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct DigitalOutputUpdateRequest_

typedef ::robot_io::DigitalOutputUpdateRequest_<std::allocator<void> > DigitalOutputUpdateRequest;

typedef boost::shared_ptr< ::robot_io::DigitalOutputUpdateRequest > DigitalOutputUpdateRequestPtr;
typedef boost::shared_ptr< ::robot_io::DigitalOutputUpdateRequest const> DigitalOutputUpdateRequestConstPtr;

// constants requiring out of line definition

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_io::DigitalOutputUpdateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_io::DigitalOutputUpdateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robot_io

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robot_io::DigitalOutputUpdateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_io::DigitalOutputUpdateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_io::DigitalOutputUpdateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_io::DigitalOutputUpdateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_io::DigitalOutputUpdateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_io::DigitalOutputUpdateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_io::DigitalOutputUpdateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d4386f6831da36b77a99649158a65fbe";
  }

  static const char* value(const ::robot_io::DigitalOutputUpdateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd4386f6831da36b7ULL;
  static const uint64_t static_value2 = 0x7a99649158a65fbeULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_io::DigitalOutputUpdateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_io/DigitalOutputUpdateRequest";
  }

  static const char* value(const ::robot_io::DigitalOutputUpdateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_io::DigitalOutputUpdateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 request_type\n\
uint32 bit_index\n\
bool output_bit_state\n\
\n\
uint32 COUNT=8\n\
uint32 SUCTION1_ON=1\n\
uint32 SUCTION2_ON=2\n\
uint32 COLLISION=0\n\
";
  }

  static const char* value(const ::robot_io::DigitalOutputUpdateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_io::DigitalOutputUpdateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.request_type);
      stream.next(m.bit_index);
      stream.next(m.output_bit_state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct DigitalOutputUpdateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_io::DigitalOutputUpdateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_io::DigitalOutputUpdateRequest_<ContainerAllocator>& v)
  {
    s << indent << "request_type: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.request_type);
    s << indent << "bit_index: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.bit_index);
    s << indent << "output_bit_state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.output_bit_state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_IO_MESSAGE_DIGITALOUTPUTUPDATEREQUEST_H
