set(collision_avoidance_pick_and_place_MESSAGE_FILES "")
set(collision_avoidance_pick_and_place_SERVICE_FILES "/home/conghui/industrial_training/training/ref/demo_manipulation/src/collision_avoidance_pick_and_place/srv/GetTargetPose.srv")
